/**
 * Stripe Connect Controller — Change #1: stripe-connect-accounts
 *
 * Admin + seller HTTP handlers for the connected-account lifecycle.
 * Admin actions live under `/api/admin/sellers/:id/stripe-connect/*`.
 * Seller self-service actions live under `/api/seller/stripe-connect/*`.
 *
 * Responsibilities:
 *   - Validate pre-conditions (fiscal data present, account exists, etc.)
 *   - Orchestrate calls to stripeConnectService
 *   - Persist the returned account_id and trigger a status sync
 *   - Send onboarding links via email
 */
const { db } = require('../config/database');
const { ApiError } = require('../middleware/errorHandler');
const { sendSuccess, sendCreated } = require('../utils/response');
const stripeConnectService = require('../services/stripeConnectService');
const emailService = require('../services/emailService');
const logger = require('../config/logger');

/**
 * Load a seller row by id, 404 if missing or wrong role.
 * @private
 */
async function loadSellerOrThrow(sellerId) {
  const result = await db.execute({
    sql: `SELECT * FROM users WHERE id = ? AND role = 'seller'`,
    args: [sellerId],
  });
  if (result.rows.length === 0) {
    throw new ApiError(404, 'Seller not found');
  }
  return result.rows[0];
}

/**
 * Load any user by id, 404 if missing (used for the seller self-service endpoints
 * where `req.user` already proves authentication but we want a fresh DB read).
 * @private
 */
async function loadUserOrThrow(userId) {
  const result = await db.execute({
    sql: `SELECT * FROM users WHERE id = ?`,
    args: [userId],
  });
  if (result.rows.length === 0) {
    throw new ApiError(404, 'User not found');
  }
  return result.rows[0];
}

/**
 * Assert that the seller has all required fiscal fields populated.
 * @private
 */
function assertFiscalDataComplete(seller) {
  const required = [
    'tax_status',
    'tax_id',
    'fiscal_full_name',
    'fiscal_address_line1',
    'fiscal_address_postal_code',
    'fiscal_address_city',
    'fiscal_address_province',
  ];
  const missing = required.filter((f) => !seller[f]);
  if (missing.length > 0) {
    throw new ApiError(400, 'Fiscal data must be filled before creating the connected account');
  }
}

// ─── Admin endpoints ──────────────────────────────────────────────

/**
 * POST /api/admin/sellers/:id/stripe-connect/create
 * Idempotent: if the seller already has an account, returns it instead of creating a duplicate.
 */
async function createAccountForSeller(req, res, next) {
  try {
    const sellerId = parseInt(req.params.id, 10);
    if (!Number.isFinite(sellerId)) {
      throw new ApiError(400, 'Invalid seller id');
    }

    const seller = await loadSellerOrThrow(sellerId);

    // Idempotency: if already exists, short-circuit without calling Stripe.
    if (seller.stripe_connect_account_id) {
      return sendSuccess(res, {
        stripe_connect_account_id: seller.stripe_connect_account_id,
        stripe_connect_status: seller.stripe_connect_status,
        already_existed: true,
      });
    }

    assertFiscalDataComplete(seller);

    const account = await stripeConnectService.createConnectedAccount({ user: seller });

    await db.execute({
      sql: `UPDATE users
            SET stripe_connect_account_id = ?,
                stripe_connect_status = 'pending'
            WHERE id = ?`,
      args: [account.id, sellerId],
    });

    // Re-fetch so syncAccountStatus sees the new account_id.
    const updatedSeller = await loadUserOrThrow(sellerId);
    await stripeConnectService.syncAccountStatus({ user: updatedSeller, account });

    logger.info(
      { sellerId, stripeAccountId: account.id, adminId: req.user?.id },
      '[stripe-connect] account created by admin'
    );

    return sendCreated(res, {
      stripe_connect_account_id: account.id,
      stripe_connect_status: 'pending',
    });
  } catch (err) {
    next(err);
  }
}

/**
 * POST /api/admin/sellers/:id/stripe-connect/onboarding-link
 */
async function generateOnboardingLinkForSeller(req, res, next) {
  try {
    const sellerId = parseInt(req.params.id, 10);
    if (!Number.isFinite(sellerId)) {
      throw new ApiError(400, 'Invalid seller id');
    }

    const seller = await loadSellerOrThrow(sellerId);
    if (!seller.stripe_connect_account_id) {
      throw new ApiError(409, 'Connected account must be created first');
    }

    const link = await stripeConnectService.createOnboardingLink({
      stripeAccountId: seller.stripe_connect_account_id,
    });

    logger.info(
      { sellerId, adminId: req.user?.id, expiresAt: link.expires_at },
      '[stripe-connect] onboarding link generated by admin'
    );

    return sendSuccess(res, { url: link.url, expires_at: link.expires_at });
  } catch (err) {
    next(err);
  }
}

/**
 * POST /api/admin/sellers/:id/stripe-connect/onboarding-link/email
 */
async function sendOnboardingLinkEmail(req, res, next) {
  try {
    const sellerId = parseInt(req.params.id, 10);
    if (!Number.isFinite(sellerId)) {
      throw new ApiError(400, 'Invalid seller id');
    }

    const seller = await loadSellerOrThrow(sellerId);
    if (!seller.stripe_connect_account_id) {
      throw new ApiError(409, 'Connected account must be created first');
    }

    const link = await stripeConnectService.createOnboardingLink({
      stripeAccountId: seller.stripe_connect_account_id,
    });

    await emailService.sendSellerOnboardingLink({ seller, url: link.url });

    logger.info(
      { sellerId, adminId: req.user?.id, recipient: seller.email },
      '[stripe-connect] onboarding link emailed by admin'
    );

    return sendSuccess(res, { sent: true, expires_at: link.expires_at });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/admin/sellers/:id/stripe-connect/status
 * Forces a sync against Stripe and returns the updated local state.
 */
async function syncStatusForSeller(req, res, next) {
  try {
    const sellerId = parseInt(req.params.id, 10);
    if (!Number.isFinite(sellerId)) {
      throw new ApiError(400, 'Invalid seller id');
    }

    const seller = await loadSellerOrThrow(sellerId);
    if (!seller.stripe_connect_account_id) {
      throw new ApiError(409, 'Connected account must be created first');
    }

    await stripeConnectService.syncAccountStatus({ user: seller });
    const fresh = await loadUserOrThrow(sellerId);

    return sendSuccess(res, {
      stripe_connect_status: fresh.stripe_connect_status,
      stripe_transfers_capability_active: fresh.stripe_transfers_capability_active === 1,
      stripe_connect_requirements_due: fresh.stripe_connect_requirements_due
        ? JSON.parse(fresh.stripe_connect_requirements_due)
        : [],
      stripe_connect_last_synced_at: fresh.stripe_connect_last_synced_at,
    });
  } catch (err) {
    next(err);
  }
}

// ─── Seller self-service endpoints ────────────────────────────────

/**
 * POST /api/seller/stripe-connect/onboarding-link
 * Seller generates their own onboarding link (operates on req.user.id).
 */
async function generateOnboardingLinkForSelf(req, res, next) {
  try {
    if (req.user?.role !== 'seller') {
      throw new ApiError(403, 'Forbidden');
    }

    const seller = await loadUserOrThrow(req.user.id);
    if (!seller.stripe_connect_account_id) {
      throw new ApiError(409, 'Your account is not yet set up. Contact 140d Galería de Arte.');
    }

    const link = await stripeConnectService.createOnboardingLink({
      stripeAccountId: seller.stripe_connect_account_id,
    });

    return sendSuccess(res, { url: link.url, expires_at: link.expires_at });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/seller/stripe-connect/status
 * Reads the seller's current stored state — does NOT force a Stripe sync
 * (webhook and /return endpoint handle that).
 */
async function getStatusForSelf(req, res, next) {
  try {
    if (req.user?.role !== 'seller') {
      throw new ApiError(403, 'Forbidden');
    }

    const seller = await loadUserOrThrow(req.user.id);

    return sendSuccess(res, {
      stripe_connect_status: seller.stripe_connect_status,
      stripe_connect_account_id: seller.stripe_connect_account_id,
      stripe_transfers_capability_active: seller.stripe_transfers_capability_active === 1,
      stripe_connect_requirements_due: seller.stripe_connect_requirements_due
        ? JSON.parse(seller.stripe_connect_requirements_due)
        : [],
      stripe_connect_last_synced_at: seller.stripe_connect_last_synced_at,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * POST /api/seller/stripe-connect/login-link
 * Generates a single-use Express Dashboard login link for the authenticated seller.
 */
async function generateLoginLinkForSelf(req, res, next) {
  try {
    if (req.user?.role !== 'seller') {
      throw new ApiError(403, 'Forbidden');
    }

    const seller = await loadUserOrThrow(req.user.id);
    if (!seller.stripe_connect_account_id) {
      throw new ApiError(409, 'Your connected account has not been created yet.');
    }

    const status = seller.stripe_connect_status;
    if (status === 'rejected' || status === 'not_started') {
      throw new ApiError(409, 'Your connected account is not eligible for dashboard access.');
    }

    const link = await stripeConnectService.createLoginLink(seller.stripe_connect_account_id);

    logger.info(
      { userId: req.user.id, stripeAccountId: seller.stripe_connect_account_id },
      '[stripe-connect] login link generated by seller'
    );

    return sendSuccess(res, { url: link.url });
  } catch (err) {
    next(err);
  }
}

module.exports = {
  createAccountForSeller,
  generateOnboardingLinkForSeller,
  sendOnboardingLinkEmail,
  syncStatusForSeller,
  generateOnboardingLinkForSelf,
  generateLoginLinkForSelf,
  getStatusForSelf,
};
