'use client'

/**
 * StripeConnectLinkModal — Change #1: stripe-connect-accounts
 *
 * Shown after an admin successfully generates an onboarding link for a
 * connected account. Lets the admin copy the URL or send it via email.
 *
 * Link URLs generated by Stripe AccountLink expire (~15min by default),
 * so we surface the expiry prominently to prevent stale shares.
 */
import { useEffect, useState } from 'react'
import { Dialog, DialogBackdrop, DialogPanel, DialogTitle } from '@headlessui/react'
import { DocumentDuplicateIcon, EnvelopeIcon, LinkIcon } from '@heroicons/react/24/outline'
import { adminAPI } from '@/lib/api'
import { useNotification } from '@/contexts/NotificationContext'

function formatExpires(expiresAt) {
  if (!expiresAt) return null
  try {
    const expiry = typeof expiresAt === 'number'
      ? new Date(expiresAt * 1000)
      : new Date(expiresAt)
    const now = new Date()
    const diffMs = expiry.getTime() - now.getTime()
    if (diffMs <= 0) return 'Expirado'
    const minutes = Math.floor(diffMs / 60000)
    if (minutes < 60) return `Expira en ${minutes} min`
    const hours = Math.floor(minutes / 60)
    return `Expira en ${hours}h ${minutes % 60}min`
  } catch {
    return null
  }
}

export default function StripeConnectLinkModal({
  isOpen,
  onClose,
  url,
  expiresAt,
  sellerEmail,
  sellerId,
}) {
  const { showSuccess, showApiError } = useNotification()
  const [sendingEmail, setSendingEmail] = useState(false)
  const [expiryLabel, setExpiryLabel] = useState(() => formatExpires(expiresAt))

  // Re-compute expiry label every 30s while the modal is open so the user
  // sees it count down rather than holding a stale value.
  useEffect(() => {
    if (!isOpen || !expiresAt) return undefined
    const id = setInterval(() => {
      setExpiryLabel(formatExpires(expiresAt))
    }, 30000)
    setExpiryLabel(formatExpires(expiresAt))
    return () => clearInterval(id)
  }, [isOpen, expiresAt])

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(url)
      showSuccess('Copiado', 'El enlace se ha copiado al portapapeles.')
    } catch {
      showApiError({
        response: {
          title: 'No se pudo copiar',
          message: 'Tu navegador bloqueó el acceso al portapapeles. Copia la URL manualmente.',
        },
      })
    }
  }

  async function handleSendEmail() {
    if (!sellerId) return
    setSendingEmail(true)
    try {
      await adminAPI.stripeConnect.sendLinkEmail(sellerId)
      showSuccess('Email enviado', `Enlace enviado a ${sellerEmail}.`)
    } catch (err) {
      showApiError(err)
    } finally {
      setSendingEmail(false)
    }
  }

  return (
    <Dialog open={isOpen} onClose={onClose} className="relative z-50">
      <DialogBackdrop
        transition
        className="fixed inset-0 bg-gray-500/75 transition-opacity data-[closed]:opacity-0 data-[enter]:duration-300 data-[leave]:duration-200 data-[enter]:ease-out data-[leave]:ease-in"
      />
      <div className="fixed inset-0 z-50 w-screen overflow-y-auto">
        <div className="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
          <DialogPanel
            transition
            className="relative transform overflow-hidden rounded-lg bg-white px-4 pt-5 pb-4 text-left shadow-xl transition-all data-[closed]:translate-y-4 data-[closed]:opacity-0 data-[enter]:duration-300 data-[leave]:duration-200 data-[enter]:ease-out data-[leave]:ease-in sm:my-8 sm:w-full sm:max-w-xl sm:p-6 data-[closed]:sm:translate-y-0 data-[closed]:sm:scale-95"
          >
            <div className="sm:flex sm:items-start">
              <div className="mx-auto flex size-12 shrink-0 items-center justify-center rounded-full bg-indigo-100 sm:mx-0 sm:size-10">
                <LinkIcon className="size-6 text-indigo-600" aria-hidden="true" />
              </div>
              <div className="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left w-full">
                <DialogTitle as="h3" className="text-base font-semibold text-gray-900">
                  Enlace de onboarding generado
                </DialogTitle>
                <p className="mt-2 text-sm text-gray-500">
                  Comparte este enlace con el artista para que complete su cuenta de pagos.
                  {expiryLabel && (
                    <>
                      {' '}
                      <span className="font-medium text-gray-700">{expiryLabel}.</span>
                    </>
                  )}
                </p>

                <div className="mt-4">
                  <label htmlFor="stripe-connect-url" className="sr-only">
                    URL de onboarding
                  </label>
                  <input
                    id="stripe-connect-url"
                    type="text"
                    readOnly
                    value={url || ''}
                    onFocus={(e) => e.target.select()}
                    className="block w-full rounded-md border-0 px-3 py-2 text-sm text-gray-900 shadow-xs ring-1 ring-inset ring-gray-300 font-mono"
                  />
                </div>
              </div>
            </div>

            <div className="mt-5 sm:mt-6 sm:flex sm:flex-row-reverse sm:gap-2">
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex w-full items-center justify-center rounded-md bg-black px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-gray-900 sm:w-auto"
              >
                <DocumentDuplicateIcon className="mr-1.5 size-4" aria-hidden="true" />
                Copiar
              </button>
              {sellerEmail && (
                <button
                  type="button"
                  onClick={handleSendEmail}
                  disabled={sendingEmail}
                  className="mt-3 inline-flex w-full items-center justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 disabled:opacity-60 disabled:cursor-not-allowed sm:mt-0 sm:w-auto"
                >
                  <EnvelopeIcon className="mr-1.5 size-4" aria-hidden="true" />
                  {sendingEmail ? 'Enviando…' : `Enviar a ${sellerEmail}`}
                </button>
              )}
              <button
                type="button"
                onClick={onClose}
                className="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-xs ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto"
              >
                Cerrar
              </button>
            </div>
          </DialogPanel>
        </div>
      </div>
    </Dialog>
  )
}
